# Generated by Django 6.0.3 on 2026-03-25 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_post_likes_alter_like_post_alter_like_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='My Site', max_length=200)),
                ('admin_email', models.EmailField(default='admin@example.com', max_length=254)),
                ('admin_name', models.CharField(default='Admin', max_length=100)),
                ('admin_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('maintenance_mode', models.CharField(choices=[('on', 'On'), ('off', 'Off')], default='off', max_length=10)),
                ('maintenance_message', models.TextField(blank=True, null=True)),
                ('maintenance_schedule', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='follower',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='follower',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('user', 'follower')},
        ),
    ]
