# Generated by Django 6.0.3 on 2026-03-21 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_like_post_alter_like_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
